name: Deploy Main

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: production
      url: https://engenharia-de-software.h4ad.workers.dev
    steps:
      - uses: actions/checkout@v3

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          preCommands: npm ci
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
